### ISSUE TITLE
Develop HTML styling for ITU documents

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-itu-style#1]
Necessary information fully available here: https://github.com/riboseinc/metanorma-itu-style

Similar with the NIST work, we want a new HTML look for ITU documents. 

@pierrefortier do you have time for this? Thanks in advance! 👍 

cc: @opoudjis just to let you know the existence of this repo.

**Comment by ronaldtse** [comment]
Thanks for the acknowledgement @pierrefortier  😉

**Comment by pierrefortier** [comment]
Hi @ronaldtse!

Here's a first draft of the styling.

Thanks!

[ITU-style-v1.zip](https://github.com/riboseinc/metanorma-itu-style/files/2907226/ITU-style-v1.zip)

**Comment by ronaldtse** [comment]
@pierrefortier thank you! I was thinking if the left bar and the middle separator could also take some colors from the orange and red? What do you think?

**Comment by pierrefortier** [comment]
Sure thing! Here is an update:

[ITU-style-v2.zip](https://github.com/riboseinc/metanorma-itu-style/files/2915435/ITU-style-v2.zip)

**Comment by ronaldtse** [comment]
Thanks @pierrefortier ! The green bar on the left now looks a bit off compared to the red and orange. Could we update that a bit? Thanks!

**Comment by pierrefortier** [comment]
Sure thing. I faded the color a bit so it's not as contrasty. 

[ITU-style-v3.zip](https://github.com/riboseinc/metanorma-itu-style/files/2922345/ITU-style-v3.zip)

**Comment by ronaldtse** [comment]
Thank you @pierrefortier !

I have just commited this to master 👍
